### PR TITLE
several fixes for MacOSX

### PR DESCRIPTION
**Pull request by albertz**

### CODE REVIEW

**Comment by albertz** [comment]
This also fixes #58.
[This StackOverflow question](https://stackoverflow.com/questions/53958926/) describes one of the issues, which is fixed by 9556950b3, but all the other commits are needed as well.

**Comment by PerBothner** [comment]
Thanks!  For the jsMenus fixes, could you submit that as a pull request for upstream: https://github.com/PerBothner/jsMenus

We want to avoid global variables, especially any with a name like `mac`.  Perhaps instead:

    Menu._isMac = ....;

This should be done *after* the Menu class is defined, i.e. near the end.

**Comment by PerBothner** [comment]
For the terminal.js patch, the `mac` should also not be a global variable.  I suggest `isMac` or `isMacOS`:

    DomTerm.isMac = ...;

in `hlib/domterm-version.js.in`.  (Note that `hlib/domterm-version.js` is generated from the former.)

**Comment by PerBothner** [comment]
For the domterm-menus.js fix, in addition to using `DomTerm.isMac`, would it make sense to replace:

    mac ? 'Command+C' : 'CommandOrControl+Shift+C'

by:

    DomTerm.isMac ? 'Command+C' : 'Ctrl+Shift+C'

since `CommandOrControl` doesn't make sense if Mac is not relevant.

**Comment by PerBothner** [comment]
I updated hlib/jsMenus.js from upstream.  Thanks.

**Comment by albertz** [comment]
I think I covered all your comments.
Except for the server. I'm actually not really sure. I remember very roughly similar problems on MacOSX before, that is how I thought about this work around. But some Google search did not yield me anything now.

**Comment by albertz** [comment]
GitHub says this has no conflicts, so I guess it can be merged.
There are many usages of "Ctrl" already before in domterm-menus.js. Changing all of them to "Control" would be kind of unrelated to this pull request, right?

**Comment by PerBothner** [comment]
Thanks. I merged it.

_"There are many usages of "Ctrl" already before in domterm-menus.js. Changing all of them to "Control" would be kind of unrelated to this pull request, right?"_

I want the opposite: I want Ctrl (and Cmd) consistently; not Control (and Command), at least the actual displayed accellerator. However, I think it makes sense for jsMenus to "canonicalize" the names.

**Pull request merged**
