### PR TITLE
lws uses a c based backend

### PR DESCRIPTION
**Pull request by SolarAquarion**
Which means we should be asking for json-c?

### CODE REVIEW

**Comment by PerBothner** [comment]
What is supposed to be happening is that  `PKG_CHECK_MODULES(JSON_C, json-c)` in configure.ac uses the `pkg-config` command to set the variables JSON_C_CFLAGS and JSON_C_LIBS in lws-term/Makefile. The JSON_C_CFLAGS is supposed to contain the appropriate `-I` flag so `#include <json.h>` works.: on my Fedora Linux system it sets it to `-I/usr/include/json-c`.  So your proposed change seems neither needed or correct.

So the question is why this isn't working for you.  What platform are you on, and which commands did you use to build DomTerm?

**Comment by SolarAquarion** [comment]
autoreconf -vfi
    ./configure --with-qtwebengine --with-javafx --prefix=/usr

**Comment by PerBothner** [comment]
What is the result of these commands:

    pkg-config --cflags json-c
    pkg-config --libs json-c

On Fedora 31 it is respectively:

    -I/usr/include/json-c
    -ljson-c

I would expect at least the former to be the same on Arch Linux.  If not, either pkg-config is not installed properly, or there is a bug in pkg-config or json-c on Arch.

**Comment by SolarAquarion** [comment]
-I/usr/include/json-c
-ljson-c

**Pull request closed without merging**
