### PR TITLE
Support the JAVA_HOME environment variable

### LINKED ISSUE #13: Launcher script should support JAVA_HOME
JAVA_HOME is the environment variable most (in my experience, at least) programs use to determine which Java to launch a program with. It's therefore likely to already be set by most users who don't have java in their path and run some other Java program regularly.

### PR DESCRIPTION
**Pull request by rwhogg**
Closes #13

### CODE REVIEW

**Comment by PerBothner** [comment]
My first reaction is that $JAVA should take precedence over $JAVA_HOME, if both are set, since $JAVA is "more specific".  OTOH, if someone sets them both, and $JAVA is different from $JAVA_HOME/bin/java perhaps they just deserve what they get ...

**Comment by rwhogg** [comment]
> My first reaction is that $JAVA should take precedence over $JAVA_HOME, if both are set, since $JAVA is "more specific".

I have no opinion at all on this matter; I'll change it if you'd like.

**Comment by PerBothner** [comment]
I figure it's fine to check HOME_HOME before JAVA - after all more people use the former.

It might be reasonable to consider a sanity check.  Ant does:

if [ ! -x "$JAVACMD" ] ; then
    echo "Error: JAVA_HOME is not defined correctly."
    echo "  We cannot execute $JAVACMD"
    exit 1
fi

**Comment by rwhogg** [comment]
> It might be reasonable to consider a sanity check. Ant does:

```bash
if [ ! -x "$JAVACMD" ] ; then
echo "Error: JAVA_HOME is not defined correctly."
echo " We cannot execute $JAVACMD"
exit 1
fi
```

Agreed. That said, I don't think we need to lose sleep over idiot-proofing a launcher script.

**Pull request merged**
