### PR TITLE
Remove boolean function argument code-smell.

### PR DESCRIPTION
**Pull request by dune-rocks**
Using a boolean argument just to take two different code paths in a function is
often a sign the function should be split in two. I think this is a good
candidate of such a case.

### CODE REVIEW

**Comment by PerBothner** [comment]
I guess in this case, where the shared code is modest and uninteresting, it would be reasonable to split the functions.  My main concern is the exception handler: I don't know the "right" thing - but what copyThread does is probably wrong.  If we split the function we now have two places where we're probably doing the wrong thing. :-) We should probably fix that first.  Perhaps Writer parameter should be a Client (so copyThread would use client.termWriter in place of out), and then on exception we could call an error method in the Client.

Also note that copyThread is also used in PtyClient.java.

**Comment by dune-rocks** [comment]
Hmm, I'll think more about that. This was more of a "am I using GitHub properly" commit :-)
Oops about PtyClient.java, my poor mans tests didn't catch that one.

I'm also a bit concerned about using Client as we do (or I'm confused...) The `Client` class seems to me that it should be called `Inferior`, I think of the client as being the other end of the websocket. What do you think?

**Comment by PerBothner** [comment]
Yes, "Client" is ambiguous - it's closer to the X11 technology where the client is the application and the server is the display manager. "Inferior" is possible - though I wonder how common that terminology is beyond Unix geeks.  Maybe Application or Worker or ...

**Comment by PerBothner** [comment]
I think the cleanest answer s to create a new DomTermErrorWriter, which would be similar to DomTermErrorStream, but a Writer.  Then instead of copyThread(in, true, out) we'd do copyThread(in, new DomTermErrorWriter(out))).

It appears that DomTermErrorWriter would be helpful for Kawa.

**Comment by dune-rocks** [comment]
Sorry, I didn't mean for these to be associated with this pull request... I wanted to stop this request, and fix some other issues before addressing it properly.

**Pull request closed without merging**
